import Foundation

/// 生成 0700 launcher script（§5.2 方案 B）。
///
/// 关键安全设计：
/// 1. **记忆内容绝不进 script 字面量**——通过 `$(cat '<memfile>')` 引用文件展开。
///    args 里的 `$__DEVHUB_MEMORY_FILE__<path>` 占位被替换为 `$(cat '<quoted-path>')`。
/// 2. **路径用单引号包裹**——bash 单引号内除 `'` 外全部字面；embedded `'` 转义为 `'\''`。
/// 3. **权限 0700**。
public final class LauncherScriptBuilder: @unchecked Sendable {

    public static let shared = LauncherScriptBuilder()

    public let cacheRoot: URL
    private let pendingCleanupLock = NSLock()
    private var pendingCleanupPaths: [String: [String]] = [:]

    public init(cacheRoot: URL? = nil) {
        if let r = cacheRoot {
            self.cacheRoot = r
        } else {
            let caches = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first!
            self.cacheRoot = caches.appendingPathComponent("DevHub", isDirectory: true)
        }
        try? FileManager.default.createDirectory(
            at: self.cacheRoot.appendingPathComponent("launchers", isDirectory: true),
            withIntermediateDirectories: true
        )
        removeStaleTemporaryFiles(olderThan: 24 * 60 * 60)
    }

    @discardableResult
    public func write(cwd: String, executable: String, arguments: [String],
                      environment: [String: String] = [:], cleanupPaths: [String] = []) async throws -> String {
        let launchersDir = cacheRoot.appendingPathComponent("launchers", isDirectory: true)
        try FileManager.default.createDirectory(at: launchersDir, withIntermediateDirectories: true)

        let uuid = UUID()
        let scriptURL = launchersDir.appendingPathComponent("\(uuid.uuidString).sh")

        let timestamp = ISO8601DateFormatter().string(from: Date())
        var lines: [String] = []
        lines.append("#!/bin/bash")
        lines.append("# Generated by CodeReentry at \(timestamp)")
        let cleanupTargets = [scriptURL.path] + cleanupPaths
        lines.append("cleanup() { /bin/rm -f -- \(cleanupTargets.map(shellQuote).joined(separator: " ")); }")
        lines.append("trap cleanup EXIT HUP INT TERM")
        lines.append("cd \(shellQuote(cwd)) || exit 1")

        for (key, value) in environment.sorted(by: { $0.key < $1.key }) {
            guard Self.isValidEnvironmentKey(key) else {
                throw LauncherScriptError.invalidEnvironmentKey(key)
            }
            lines.append("export \(key)=\(shellQuote(value))")
        }

        let renderedArgs = arguments.map { renderArg($0) }.joined(separator: " ")
        lines.append("\(shellQuote(executable))\(renderedArgs.isEmpty ? "" : " " + renderedArgs)")
        lines.append("status=$?")
        lines.append("exit \"$status\"")

        let body = lines.joined(separator: "\n") + "\n"
        guard FileManager.default.createFile(
            atPath: scriptURL.path,
            contents: Data(body.utf8),
            attributes: [.posixPermissions: 0o700]
        ) else {
            throw LauncherScriptError.cannotCreateScript(scriptURL.path)
        }

        pendingCleanupLock.withLock {
            // Launchers delete themselves after execution. Prune those completed
            // entries before recording the new manual-recovery candidate.
            pendingCleanupPaths = pendingCleanupPaths.filter {
                FileManager.default.fileExists(atPath: $0.key)
            }
            pendingCleanupPaths[scriptURL.standardizedFileURL.path] = cleanupPaths
        }

        return scriptURL.path
    }

    /// Return a paste-ready command that executes a generated launcher without
    /// exposing the launcher's arguments or environment on the clipboard.
    /// The path is quoted with the same rules used inside launcher scripts.
    public func invocationCommand(for launcherPath: String) -> String {
        "/bin/bash \(shellQuote(launcherPath))"
    }

    /// Remove a launcher the user chose not to run. Only UUID-named files inside
    /// this builder's exact launchers directory are accepted, so a forged error
    /// cannot turn the recovery UI into an arbitrary-file deletion primitive.
    public func discardLauncher(at launcherPath: String) throws {
        let candidate = URL(fileURLWithPath: launcherPath).standardizedFileURL
        let launchersDirectory = cacheRoot
            .appendingPathComponent("launchers", isDirectory: true)
            .standardizedFileURL
        guard candidate.deletingLastPathComponent() == launchersDirectory,
              candidate.pathExtension == "sh",
              UUID(uuidString: candidate.deletingPathExtension().lastPathComponent) != nil else {
            throw LauncherScriptError.unmanagedLauncher(launcherPath)
        }
        let companions = pendingCleanupLock.withLock {
            pendingCleanupPaths.removeValue(forKey: candidate.path) ?? []
        }
        if FileManager.default.fileExists(atPath: candidate.path) {
            try FileManager.default.removeItem(at: candidate)
        }
        for companionPath in companions {
            guard let companion = managedInjectionURL(for: companionPath) else { continue }
            if FileManager.default.fileExists(atPath: companion.path) {
                try FileManager.default.removeItem(at: companion)
            }
        }
    }

    /// 清理由崩溃/强制退出遗留的 launcher 与注入文件。正常退出由脚本 trap 即时删除。
    public func removeStaleTemporaryFiles(olderThan age: TimeInterval, now: Date = Date()) {
        for directoryName in ["launchers", "injection"] {
            let directory = cacheRoot.appendingPathComponent(directoryName, isDirectory: true)
            guard let files = try? FileManager.default.contentsOfDirectory(
                at: directory, includingPropertiesForKeys: [.contentModificationDateKey],
                options: [.skipsHiddenFiles]
            ) else { continue }
            for file in files {
                let modified = (try? file.resourceValues(forKeys: [.contentModificationDateKey]).contentModificationDate) ?? now
                if now.timeIntervalSince(modified) > age {
                    try? FileManager.default.removeItem(at: file)
                }
            }
        }
        pendingCleanupLock.withLock {
            pendingCleanupPaths = pendingCleanupPaths.filter {
                FileManager.default.fileExists(atPath: $0.key)
            }
        }
    }

    private func managedInjectionURL(for path: String) -> URL? {
        let candidate = URL(fileURLWithPath: path).standardizedFileURL
        let injectionDirectory = cacheRoot
            .appendingPathComponent("injection", isDirectory: true)
            .standardizedFileURL
        guard candidate.deletingLastPathComponent() == injectionDirectory,
              candidate.pathExtension == "md",
              UUID(uuidString: candidate.deletingPathExtension().lastPathComponent) != nil else {
            return nil
        }
        return candidate
    }

    private static func isValidEnvironmentKey(_ key: String) -> Bool {
        key.range(of: #"^[A-Za-z_][A-Za-z0-9_]*$"#, options: .regularExpression) != nil
    }

    /// bash 单引号引用：内部 `'` 转义为 `'\''`。
    private func shellQuote(_ s: String) -> String {
        return "'" + s.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    /// 渲染单个 argument。
    /// `$__DEVHUB_MEMORY_FILE__<path>` → `"$(cat '<quoted-path>')"`
    ///   外包双引号防止 word-splitting 和 globbing（否则多行/含空格的记忆会
    ///   被拆成多个 argv，含 `*` 的内容会展开 cwd 文件名——参数注入风险）。
    /// 其余 → `'<quoted-arg>'`
    private func renderArg(_ arg: String) -> String {
        let marker = "$__DEVHUB_MEMORY_FILE__"
        if arg.hasPrefix(marker) {
            let path = String(arg.dropFirst(marker.count))
            return "\"$(cat \(shellQuote(path)))\""
        }
        return shellQuote(arg)
    }
}

public enum LauncherScriptError: Error, Equatable {
    case invalidEnvironmentKey(String)
    case cannotCreateScript(String)
    case unmanagedLauncher(String)
}
